set_property IOSTANDARD LVCMOS33 [get_ports {hex_gridA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_gridA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_gridA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_gridA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_segA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_Clear]
set_property IOSTANDARD LVCMOS33 [get_ports Run_Accumulate]
set_property PACKAGE_PIN G6 [get_ports {hex_gridA[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_gridA[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_gridA[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_gridA[3]}]
set_property PACKAGE_PIN E6 [get_ports {hex_segA[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_segA[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_segA[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_segA[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_segA[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_segA[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_segA[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_segA[7]}]
set_property PACKAGE_PIN G1 [get_ports {SW[0]}]
set_property PACKAGE_PIN F2 [get_ports {SW[1]}]
set_property PACKAGE_PIN F1 [get_ports {SW[2]}]
set_property PACKAGE_PIN E2 [get_ports {SW[3]}]
set_property PACKAGE_PIN E1 [get_ports {SW[4]}]
set_property PACKAGE_PIN D2 [get_ports {SW[5]}]
set_property PACKAGE_PIN D1 [get_ports {SW[6]}]
set_property PACKAGE_PIN C2 [get_ports {SW[7]}]
set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN J2 [get_ports Reset_Clear]
set_property PACKAGE_PIN J1 [get_ports Run_Accumulate]

set_property IOSTANDARD LVCMOS33 [get_ports {Aval[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Aval[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bval[0]}]
set_property PACKAGE_PIN C17 [get_ports {Aval[0]}]
set_property PACKAGE_PIN B18 [get_ports {Aval[1]}]
set_property PACKAGE_PIN A17 [get_ports {Aval[2]}]
set_property PACKAGE_PIN B17 [get_ports {Aval[3]}]
set_property PACKAGE_PIN C18 [get_ports {Aval[4]}]
set_property PACKAGE_PIN D18 [get_ports {Aval[5]}]
set_property PACKAGE_PIN E18 [get_ports {Aval[6]}]
set_property PACKAGE_PIN G17 [get_ports {Aval[7]}]
set_property PACKAGE_PIN C13 [get_ports {Bval[0]}]
set_property PACKAGE_PIN C14 [get_ports {Bval[1]}]
set_property PACKAGE_PIN D14 [get_ports {Bval[2]}]
set_property PACKAGE_PIN D15 [get_ports {Bval[3]}]
set_property PACKAGE_PIN D16 [get_ports {Bval[4]}]
set_property PACKAGE_PIN F18 [get_ports {Bval[5]}]
set_property PACKAGE_PIN E17 [get_ports {Bval[6]}]
set_property PACKAGE_PIN D17 [get_ports {Bval[7]}]
set_property PACKAGE_PIN C9 [get_ports Xval]
set_property IOSTANDARD LVCMOS33 [get_ports Xval]

create_clock -period 20.000 -name Clk -waveform {0.000 10.000} [get_ports Clk]

connect_debug_port u_ila_0/probe2 [get_nets [list {run_once/FSM_onehot_curr_state[0]_i_1_n_0}]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Bval_OBUF[0]} {Bval_OBUF[1]} {Bval_OBUF[2]} {Bval_OBUF[3]} {Bval_OBUF[4]} {Bval_OBUF[5]} {Bval_OBUF[6]} {Bval_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Aval_OBUF[0]} {Aval_OBUF[1]} {Aval_OBUF[2]} {Aval_OBUF[3]} {Aval_OBUF[4]} {Aval_OBUF[5]} {Aval_OBUF[6]} {Aval_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {SW_IBUF[0]} {SW_IBUF[1]} {SW_IBUF[2]} {SW_IBUF[3]} {SW_IBUF[4]} {SW_IBUF[5]} {SW_IBUF[6]} {SW_IBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Run_Accumulate_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_IBUF_BUFG]
