# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/cherr/Downloads/lab7_1_provided_fa23_2/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_0_1/mb_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_0 || ORIG_REF_NAME==mb_block_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_v10_0_2/mb_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_v10_0 || ORIG_REF_NAME==mb_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_v10_0_2/mb_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_v10_0 || ORIG_REF_NAME==mb_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_0_2/mb_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_0_2/mb_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_lmb_bram_0_2/mb_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_lmb_bram_0 || ORIG_REF_NAME==mb_block_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xbar_0_2/mb_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xbar_0 || ORIG_REF_NAME==mb_block_xbar_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_periph_0_2/mb_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mdm_1_0_2/mb_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mdm_1_0 || ORIG_REF_NAME==mb_block_mdm_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_clk_wiz_1_0_1/mb_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_clk_wiz_1_0 || ORIG_REF_NAME==mb_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0_2/mb_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_uartlite_0_0_2/mb_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_uartlite_0_0 || ORIG_REF_NAME==mb_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0_2/mb_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_hdmi_text_controller_0_24/mb_block_hdmi_text_controller_0_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_hdmi_text_controller_0_24 || ORIG_REF_NAME==mb_block_hdmi_text_controller_0_24} -quiet] -quiet

# XDC: c:/Users/cherr/ECE385_Lab7v1/ECE385_Lab7v1.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
